# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  python: circleci/python@0.2.1


jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/devops2022


    steps:
        - checkout:
        -run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
        -run:
            name: run tests
            command: |
              . venv/bin/activate
              flake8 --exclude=venv* --statistics
              #pytest --v --cov=calculator
              pytest --junitxml=test-results/junit.xml
          - store_test_results
            path: test_results
          - store_artifacts:
              path: test-results

   